site_name: My Mathematics Notes

theme:
  name: material

nav:
  - Home: index.md
  - Interactive Explorations:
    - Explorations Home: interactive_explorations/index.md
    - Geometry:
        - Geometry Explorations Home: interactive_explorations/geom/index.md
        - Trigonometric Graphs: 
          - Trigonometric Graphs: interactive_explorations/geom/trig.md
          - The Sine Graph: interactive_explorations/geom/sine_cos.md
          - The Cosine Graph: interactive_explorations/geom/cosine.md
          - Modelling a Ferris Wheel: interactive_explorations/geom/ferris.md
  - IB Topical Questions and Solutions: 
    - Home: ib_topical/index.md
    - SL MAA: 
      - SL MAA Home: ib_topical/sl_topical/number/index.md
      - Number and Algebra: ib_topical/sl_topical/number/index.md
      - Functions and Graphs: 
        - Home: ib_topical/sl_topical/function/index.md
        - Basic Questions: ib_topical/sl_topical/function/basic.md
      - Geometry and Trigonometry: ib_topical/sl_topical/geometry/index.md
      - Calculus: ib_topical/sl_topical/calc/index.md
      - Probability and Statistics: ib_topical/sl_topical/stats/index.md
      - Back to Home: index.md
    - HL MAA: 
      - HL MAA Home: ib_topical/hl_topical/index.md
      - Number and Algebra: ib_topical/hl_topical/number/index.md
      - Functions and Graphs: ib_topical/hl_topical/function/index.md
      - Geometry and Trigonometry: ib_topical/hl_topical/geometry/index.md
      - Calculus: ib_topical/hl_topical/calc/index.md
      - Probability and Statistics: ib_topical/hl_topical/stats/index.md
      - Back to Home: index.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css