site_name: My Mathematics Notes

theme:
  name: material

nav:
  - Home: index.md
  - Interactive Explorations:
    - Home: interactive_explorations/index.md
    - Geometry:
        - Home: interactive_explorations/geom/index.md
        - Trigonometric Graphs from the Unit Circle: interactive_explorations/geom/trig_graph_circle.md
  - IB Topical Questions and Solutions: ib_topical/index.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js